language: go
sudo: false

before_install:
  - echo 'before_install'

install:
  - echo 'install'

jobs:
  include:
    - stage: test
      before_script:
        - env        
        - git clone "https://github.com/${TRAVIS_REPO_SLUG}.wiki.git"
        - cd "$(basename ${TRAVIS_REPO_SLUG})".wiki
        - ls -hal
        - cat Home.md
        - go version
      script:
        - echo 'Script'
